apiVersion: v1
kind: Config
clusters:
- name: eks-production
  cluster:
    certificate-authority-data: 
    server: https://AB1BC29BD15329D813D22E838CCB7975.gr7.us-east-1.eks.amazonaws.com
contexts:
- name: prometheus-context
  context:
    cluster: eks-production
    user: prometheus-sa
current-context: prometheus-context
users:
- name: prometheus-sa
  user:
    token: 
